#!/usr/bin/env python3

import os
import sys
import json
import requests
from datetime import date
from pathlib import Path

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
REPO_NAME    = os.environ.get("REPO_NAME", "")
MAINTAINER   = "KashishOO7"


def load_report() -> dict:
    path = Path("audit_report.json")
    if not path.exists():
        return {"date": date.today().isoformat(), "item_count": 0, "finding_count": 0, "findings": []}
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_validate_output() -> str:
    path = Path("audit_validate.txt")
    if not path.exists():
        return "_validate.ts output not available._"
    content = path.read_text(encoding="utf-8").strip()
    return content[:3000] if len(content) > 3000 else content


def severity_emoji(level: str) -> str:
    return {"critical": "🔴", "red": "🟠", "amber": "🟡"}.get(level, "⚪")


def build_issue_body(report: dict, validate_output: str) -> str:
    lines = []
    lines.append(f"# Spectra Audit Report — {report['date']}\n")
    lines.append(
        f"**Items scanned:** {report['item_count']}  \n"
        f"**Findings:** {report['finding_count']}\n"
    )
    lines.append(
        "_Auto-generated by the Spectra Internal Audit workflow. "
        "Review findings, apply fixes where needed, then close this issue._\n"
    )
    lines.append("---\n")

    findings = report.get("findings", [])
    if not findings:
        lines.append("✅ **No findings.** All items pass staleness, integrity, and cross-reference checks.\n")
    else:
        by_check: dict[str, list] = {}
        for f in findings:
            by_check.setdefault(f["check"], []).append(f)

        check_labels = {
            "staleness": "Content Staleness",
            "deprecated_integrity": "Deprecated Items Missing superseded_by",
            "source_integrity": "Active Items Missing Primary Source",
            "cross_reference": "Broken Cross-References",
            "landscape_triage": "Untriaged Landscape Issues",
        }

        for check_key, check_findings in by_check.items():
            label = check_labels.get(check_key, check_key)
            lines.append(f"## {label}\n")
            for f in check_findings:
                emoji = severity_emoji(f["level"])
                lines.append(f"- {emoji} **{f['id']}** — {f['detail']}")
                lines.append(f"  `{f['file']}`\n")
            lines.append("")

    lines.append("---\n")
    lines.append("## validate.ts Output\n")
    lines.append(f"```\n{validate_output}\n```\n")
    lines.append(
        "---\n"
        "_Auto-generated by `spectra-audit.yml`. Close once reviewed._"
    )
    return "\n".join(lines)


def ensure_label_exists(headers: dict) -> None:
    url = f"https://api.github.com/repos/{REPO_NAME}/labels"
    try:
        res = requests.get(url, headers=headers, timeout=10)
        existing = {l["name"] for l in res.json()} if res.status_code == 200 else set()
        if "audit-report" not in existing:
            requests.post(
                url,
                headers=headers,
                json={"name": "audit-report", "color": "0075ca", "description": "Automated audit report"},
                timeout=10,
            )
    except Exception:
        pass


def post_issue(title: str, body: str) -> None:
    if not GITHUB_TOKEN or not REPO_NAME:
        print("Missing GITHUB_TOKEN or REPO_NAME.", flush=True)
        sys.exit(1)

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    ensure_label_exists(headers)

    url = f"https://api.github.com/repos/{REPO_NAME}/issues"
    payload = {
        "title": title,
        "body": body,
        "labels": ["audit-report"],
        "assignees": [MAINTAINER],
    }
    try:
        res = requests.post(url, headers=headers, json=payload, timeout=15)
        res.raise_for_status()
        print(f"Audit issue created: {res.json().get('html_url', '')}", flush=True)
    except Exception as exc:
        print(f"Failed to create audit issue: {exc}", flush=True)
        sys.exit(1)


def main():
    report = load_report()
    validate_output = load_validate_output()
    finding_count = report.get("finding_count", 0)
    title = f"[Audit] Spectra content audit — {report['date']} ({finding_count} finding{'s' if finding_count != 1 else ''})"
    body = build_issue_body(report, validate_output)
    post_issue(title, body)


if __name__ == "__main__":
    main()